#!/bin/sh
#!/bin/bash

echo "
REDIS_HOST:${REDIS_HOST}
NAVER_MAIL=${NAVER_MAIL}
NAVER_PW=${NAVER_PW}

DATABASE_USER=${DATABASE_USER}
DATABASE_PWD=${DATABASE_PWD}
JWT_REFRESH=${JWT_REFRESH}
JWT_ACCESS=${JWT_ACCESS}

# google login
GOOGLE_USER=${GOOGLE_USER}
GOOGLE_PWD=${GOOGLE_PWD}
DATABASE_NAME=${DATABASE_NAME}
DATABASE_USER=${DATABASE_USER}
DATABASE_PWD=${DATABASE_PWD}
DATABASE_HOST=${DATABASE_HOST}
" > .env_spring
