FROM gradle:7.5.0-jdk11 as builder
WORKDIR /build

COPY build.gradle settings.gradle /build/
RUN gradle build -x test --parallel --continue > /dev/null 2>&1 || true

COPY . /build
RUN gradle build -x test --parallel
FROM adoptopenjdk/openjdk11:alpine
COPY --from=builder /build/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar","/app.jar"]