# Generated by Django 4.0.6 on 2022-07-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='categoty_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
