# Generated by Django 4.0.6 on 2022-07-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagmodel', '0002_tag_categoty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='categoty_id',
            new_name='category_id',
        ),
    ]
