# Generated by Django 4.1.1 on 2022-09-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codiplanmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='codiplan',
            constraint=models.UniqueConstraint(fields=('userId', 'plan_date'), name='unique codiplan for each days'),
        ),
    ]
