# Generated by Django 4.0.6 on 2022-07-25 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothmodel', '0002_cloth_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottom_cloth_req', to='clothmodel.cloth')),
                ('top_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_cloth_req', to='clothmodel.cloth')),
            ],
        ),
    ]
