# Generated by Django 4.0.6 on 2022-07-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothmodel', '0002_cloth_tags'),
        ('codimodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cody',
            new_name='Codi',
        ),
    ]
