# Generated by Django 4.0.6 on 2022-08-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codimodel', '0003_rename_bottom_id_codi_bottom_rename_top_id_codi_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='codi',
            name='userId',
            field=models.IntegerField(default=1, verbose_name='userId'),
        ),
    ]
