# Generated by Django 4.1.2 on 2022-11-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codimodel', '0005_codi_cap_codi_footwear'),
    ]

    operations = [
        migrations.AddField(
            model_name='codi',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
