# Generated by Django 4.1.2 on 2022-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codimodel', '0006_codi_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='codi',
            name='islock',
            field=models.BooleanField(default=False),
        ),
    ]
