# Generated by Django 4.1.2 on 2022-11-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codimodel', '0007_codi_islock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codi',
            options={'ordering': ('id',)},
        ),
    ]
