# Generated by Django 4.1.2 on 2022-11-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codimodel', '0008_alter_codi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codi',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
