# Generated by Django 4.0.6 on 2022-07-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cloth/%Y/%m/%d/', verbose_name='IMAGE')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DT')),
            ],
            options={
                'ordering': ('create_dt',),
            },
        ),
    ]
