# Generated by Django 4.0.6 on 2022-07-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagmodel', '0001_initial'),
        ('clothmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tagmodel.tag'),
        ),
    ]
