# Generated by Django 4.1.1 on 2022-09-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothmodel', '0003_cloth_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
